#!/bin/bash
# Composes a latex file by concatenating the latex segments contained
# in the arguments to this script.

beginning_file_name=$1
header=$2
middle_file_name=$3
body=$4
end_file_name=$5
output_filename=$6

(cat "$beginning_file_name"; \
echo "$header"; \
cat "$middle_file_name"; \
echo "$body"; \
cat "$end_file_name") > "$output_filename"
